[package]
name = "asyncscraper"
version = "0.1.0"
authors = ["iancormac84 <wilnathan@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "*"
failure = "*"
futures = "0.1.25"
http = "0.1.13"
hyper = "0.12.13"
hyper-tls = "0.3.1"
kuchiki = "0.7.2"
mime = "0.3.9"
mime_guess = { git = "https://github.com/abonander/mime_guess.git" }
native-tls = "*" 
streamunordered = "*"
url = "*"